version: '3.6'

services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-flame_server_1
      APP_PORT: 5005

  server:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - ${APP_DATA_DIR}/flame/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    ports:
      - 5005:5005
    environment:
      APP_PASSWORD: "$APP_PASSWORD"
    restart: unless-stopped
